### ISSUE TITLE
Make Double-Wide Browse Grid Ads Mass-Editable

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/GLOBAL#1]

**Comment by juanmriosv** [comment]
Testing testing 1, 2 ,3 @c21hornak

**Comment by juanmriosv** [comment]
This is ready for QA @c21hornak

**Comment by c21hornak** [comment]
@juanmriosv Is this done and in production?

**Comment by juanmriosv** [comment]
@c21hornak All grid adds are only pushed when needed.

**Comment by c21hornak** [comment]
This is live. Closing.
