### ISSUE TITLE
Creating Solid White CTA

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#12]
Adding Solid White Background CTA
- Inactive State: Background:white; Text-color:black.
- Hover state: Background: Black; Text-color:white.

**Comment by c21hornak** [comment]
@juanmriosv can you please provide a link to examples of this?

**Comment by juanmriosv** [comment]
@c21hornak https://www.c21stores.com/pages/cta

**Comment by c21hornak** [comment]
Got it, thanks! Approved for silent push to PROD.

**Comment by c21hornak** [comment]
@juanmriosv is this already on PROD?

**Comment by juanmriosv** [comment]
@c21hornak  Yes, silently in PROD

**Comment by c21hornak** [comment]
Ok thanks. Closing.
