### ISSUE TITLE
Mega Menus text xtra space

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#14]
![unknown](https://cloud.githubusercontent.com/assets/19403001/18154116/17308b5a-6fd0-11e6-92cb-90b52673aa92.png)

**Comment by c21hornak** [comment]
@juanmriosv what was done for this ticket?

**Comment by juanmriosv** [comment]
@c21hornak This was a fix on something you call out some weeks ago. There was xtra space at the bottom of the multiple megaMenus. I found the original Email, is dated Tuesday June 27th at 3:38 pm

**Comment by c21hornak** [comment]
Completed. Closing.
