### ISSUE TITLE
Darken Text on Mega Menus

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#18]

**Comment by c21hornak** [comment]
I'm not noticing any difference between STAGING and PROD

**Comment by juanmriosv** [comment]
It should be no difference, in both the text is slightly darker. I push the update in both production and staging

**Comment by c21hornak** [comment]
If Elisabeth was happy with the change, then let's just close this one.

**Comment by c21hornak** [comment]
Closing.
