### ISSUE TITLE
Large Square Plus One - Clickable Images

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/GLOBAL#19]
@juanmriosv looks like you have completed this but there was no ZenHub ticket for it.

https://www.staging.c21.weblinc.com/pages/jmlargesquareplusone

**Comment by AdenaG** [comment]
Pass in STAGING

**Comment by c21hornak** [comment]
Approved to push to PROD.

**Comment by c21hornak** [comment]
Juan pushed to PROD on 7/26.
