### ISSUE TITLE
Large Square +1 & Large Square +2 Content Block Enhancements for Mobile

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/GLOBAL#2]

**Comment by juanmriosv** [comment]
@c21hornak  Waiting for confirmation on: For each of these two content blocks, only the big message will show on mobile, all the smallest messages ( +1, + 2 respectively) will not show on mobile

**Comment by c21hornak** [comment]
Just wondering who originally requested this project? I know I opened the ticket because it was on your to-do list, but I don't know what the priority is.

**Comment by AdenaG** [comment]
Pass in STAGING (release)

**Comment by c21hornak** [comment]
This is live. Closing.
