### ISSUE TITLE
Five Column Square - Clickable Images

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/GLOBAL#20]
@juanmriosv looks like you have started this but there was no ZenHub ticket for it.

https://www.staging.c21.weblinc.com/pages/jmfivecolumnsquare

**Comment by c21hornak** [comment]
The first square of the 5 squares does not seem to be clickable.

**Comment by juanmriosv** [comment]
@c21hornak This should be good to go Michael

**Comment by c21hornak** [comment]
Approved to push to PROD.

**Comment by c21hornak** [comment]
Juan pushed to PROD on 7/26.
