### ISSUE TITLE
MEGA MENU STANDARDIZATION

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#21]
EPIC is for:
https://github.com/Century21Stores/GLOBAL/issues/13 — 4-small Mega Menu fix
https://github.com/Century21Stores/GLOBAL/issues/14 — Mega Menus text xtra space
https://github.com/Century21Stores/GLOBAL/issues/18 — Darken Text on Mega Menus

**Comment by c21hornak** [comment]
![screen shot 2016-08-31 at 11 16 35 pm](https://cloud.githubusercontent.com/assets/19403001/18154256/1cf2d07e-6fd1-11e6-8387-9d3e5230f7e2.png)
![screen shot 2016-08-31 at 11 16 45 pm](https://cloud.githubusercontent.com/assets/19403001/18154258/20afef8a-6fd1-11e6-9d79-f939b3028ddf.png)

**Comment by c21hornak** [comment]
Completed and closing.
