### ISSUE TITLE
PLCC Header Split with shipping information

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#28]

**Comment by juanmriosv** [comment]
@c21hornak Currently finding out about mobile

**Comment by c21hornak** [comment]
@juanmriosv this is live, right?

**Comment by juanmriosv** [comment]
@c21hornak 
Yes, I started to go over things I have not done / cleaning up tasks / still pending.
This can be closed if you agree.

**Comment by c21hornak** [comment]
Sounds good. Closing.
