### ISSUE TITLE
Remove Sold Out Members from Package Products

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/GLOBAL#32]
Note: related to https://jira.tools.weblinc.com/browse/CENTURYROR-942

**Comment by AdenaG** [comment]
Sorry for delay. I think this was merch's request - can I get clarification on requirements? 
Sold out members are removed, but the master style also gets removed from the category. I think that is what they wanted, but this ticket specifically says remove sold out members. Thanks.

**Comment by juanmriosv** [comment]
Hi @AdenaG,
all good.

Yes, this ticket is specifically to remove sold out members from a package product.

"Removing" (in some form) a package product that does not have any member will be a different story. Perhaps a different ticket.

**Comment by c21hornak** [comment]
@juanmriosv where is this one testable?

**Comment by c21hornak** [comment]
Closing.
