### ISSUE TITLE
Tiered Pricing Changes on PDP - V2

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/GLOBAL#33]

**Comment by juanmriosv** [comment]
![screen shot 2016-12-05 at 1 03 36 pm](https://cloud.githubusercontent.com/assets/16789090/20896324/428816fe-baeb-11e6-9a9b-601c7bac70ad.png)

**Comment by juanmriosv** [comment]
Hi @AdenaG ,

This is ready for QA on chrome and Firefox, and IE. (safari might have problems)

QA release environment: JMprototype (https://www.c21stores.com/pages/jmprototype)

Best,

Juan
cc. @c21hornak

**Comment by c21hornak** [comment]
@AdenaG do you have any products in PROD you can test this with?

**Comment by AdenaG** [comment]
He's an inactive one, visible in Workflow.
4079-0715
https://www.c21stores.com/products/striped-quarter-socks

Here's a couple live ones:
2703-8792 
https://www.c21stores.com/products/faux-fur-trm-zp-frnt?color=Pewter&via=5851a63669702d432b00160c%2C5851b84769702d1fb70054f0
2415-8536
https://www.c21stores.com/products/fernwood-mcknck-swtr?color=White&via=5851a63669702d432b00160c%2C5851b84769702d1fb70054f0

**Comment by AdenaG** [comment]
@juanmriosv 
Try these examples:
And PS - it shows in quickview.
https://www.c21stores.com/products/blue-mini-chk-sf
1208-2984

https://www.c21stores.com/products/signature-faux-shearling-coat?color=Whiskey+Cream&via=5851a63669702d432b00160c%2C5851b84769702d1fb70054f0
2706-7565

https://www.c21stores.com/products/faux-sherpa-trim-down-coat?color=Nickel&via=5851a63669702d432b00160c%2C5851b84769702d1fb70054f0
2712-3881

**Comment by juanmriosv** [comment]
PDP ready
https://www.c21stores.com/products/signature-faux-shearling-coat?color=Whiskey+Cream&via=5851a63669702d432b00160c%2C5851b84769702d1fb70054f0

https://www.c21stores.com/products/blue-mini-chk-sf

**Comment by AdenaG** [comment]
@juanmriosv am I viewing this live or on a release?

**Comment by juanmriosv** [comment]
yes, JMprototype.
@AdenaG

**Comment by AdenaG** [comment]
Can we also try it on a master style to make sure it doesn't wrap?

https://www.c21stores.com/products/legends-softside-upright-spinner?via=5851a63669702d432b00160c%2C5851b8a369702d2a5700539d

https://www.c21stores.com/products/amber-bath-collection?via=5851a63669702d432b00160c%2C5851b8a369702d2a5700539d

**Comment by juanmriosv** [comment]
@AdenaG This ticket is just for PDP. I have another one open for Quick View and I will open another for Masters. All are a bit different

**Comment by AdenaG** [comment]
Single item PDP looks good then.

**Comment by c21hornak** [comment]
@juanmriosv The middle price is supposed to be the same point size as the bottom price, per the V2 screenshot in this ticket.

**Comment by juanmriosv** [comment]
@c21hornak Updated in this ticket and also in Master pages and Quick View

**Comment by AdenaG** [comment]
@juanmriosv 
Savings look a little far to the left on master style parent and definitely too far away on the children tied to them on desktop.
On tablet & mobile, its even further, and alignment if off.
See screenshots    
![master style desktop](https://cloud.githubusercontent.com/assets/20344050/21623827/49dcecec-d1d2-11e6-9dc6-d36bb8895c60.png)
![master style tablet](https://cloud.githubusercontent.com/assets/20344050/21623829/4b376a18-d1d2-11e6-9208-b006a6b83789.png)
![master style mobile](https://cloud.githubusercontent.com/assets/20344050/21623830/4c60a300-d1d2-11e6-9707-fee262532965.png)

**Comment by c21hornak** [comment]
Approved to push to PROD @juanmriosv

**Comment by c21hornak** [comment]
Closing.
