### ISSUE TITLE
TIERED PRICING CHANGES - V2

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/GLOBAL#34]
This EPC contains:
• Tiered Pricing Changes on PDP (GLOBAL-33) — https://github.com/Century21Stores/GLOBAL/issues/33
• Tiered Pricing Changes on Master Product pages (GLOBAL-43) — https://github.com/Century21Stores/GLOBAL/issues/43
• Tiered Pricing Changes on Quick View (GLOBAL-42) — https://github.com/Century21Stores/GLOBAL/issues/42

**Comment by juanmriosv** [comment]
Ready on JMPrototype @AdenaG

**Comment by juanmriosv** [comment]
@c21hornak 
I've just sent all this epic to QA

**Comment by c21hornak** [comment]
Closing.
