### ISSUE TITLE
Videos on Tech Jewelry PDPs

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#36]
List of products to be added:

6612-0977
6612-1699
6612-4222
6613-0860
6613-4030
6613-9439
6614-0477
6614-0557
6614-1271
6614-0254
6614-6784
6614-5188
6614-1106
6614-0251
6614-2717
6614-8996
953971CDC56614-51886614-89966614-0477
0DA56941B76614-27176614-05576614-0254
674E56A0B56614-67846614-1271
0FD847BFAC6614-02516614-1106

We’re only going to use one video…this one, https://www.youtube.com/watch?v=UhdpwZAc0Yk. It will go on every product page for the below styles. (Nicole Simonetti)

Placement of "play" button:  "Next to: Click here to view full size" (Elisabeth)

**Comment by juanmriosv** [comment]
Preview ready on environment: JMPrototype
https://www.c21stores.com/pages/jmprototype

**Comment by juanmriosv** [comment]
Ready for QA

**Comment by c21hornak** [comment]
Looks good to me (in Chrome). Ready to QA @AdenaG . This should also work in Mobile and Tablet, Safari, IE, etc.

Activate Release: https://www.c21stores.com/pages/jmprototype
Then go to:
https://www.c21stores.com/products/929-strl-sil-blk-md-altruis-by-vinaya-7?color=Silver

**Comment by AdenaG** [comment]
Looks good in Chrome for me too, but cannot get it to display on any other browsers, mobile or tablet, or Chrome on PC, even on wifi.

**Comment by AdenaG** [comment]
Looks good to me on Chrome as well, but cannot get it to display on any other browsers on PC and Mac, mobile and tablet too.

**Comment by juanmriosv** [comment]
@AdenaG We can get together to replicate it. I am pretty sure you are not able to play video on PC because of the network. Ken had that problem all the time. I'll check the rest of devices.

**Comment by juanmriosv** [comment]
Videos should be showing "now" on IPAD and phones.
touch background to close it.(for now)

**Comment by AdenaG** [comment]
@juanmriosv Did you mean it IS supposed to show on ipad and phones?

**Comment by AdenaG** [comment]
@juanmriosv Not seeing video on ipad or iphone.

**Comment by juanmriosv** [comment]
@AdenaG  Strange, I saw it the other day I was in Jersey on both Ipad and mobile.

**Comment by c21hornak** [comment]
@AdenaG this is working on my iPhone. I'm looking at this product https://www.c21stores.com/products/928-strl-sil-blk-sml-altruis-by-vinaya-6 
also this one
https://www.c21stores.com/products/930-strl-sil-blk-lrg-altruis-by-vinaya-8
also this one
https://www.c21stores.com/products/929-strl-sil-blk-md-altruis-by-vinaya-7

**Comment by AdenaG** [comment]
Looks good. Ipad had some pending updates, so now its working.

**Comment by juanmriosv** [comment]
Pushed to production

**Comment by c21hornak** [comment]
Closing.
