### ISSUE TITLE
Tiered Pricing Changes on Quick View - V2

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#42]

**Comment by juanmriosv** [comment]
Hi @AdenaG same release (JMprototype).
I am not sure how it will look on safari (i might found the issue)
crossing fingers :)

**Comment by AdenaG** [comment]
@juanmriosv 

Savings look slightly off to the left.
![screen shot 2017-01-03 at 5 01 25 pm](https://cloud.githubusercontent.com/assets/20344050/21624772/531bbffa-d1d6-11e6-9c83-31dbf87dfee9.png)

Also, there is quickview in these sections, that should be updated as well: you may also like, recently viewed, and heart section.

**Comment by juanmriosv** [comment]
@AdenaG some browsers will render this differently, I brought it as close as possible without breaking it in other screen sizes.
Done

**Comment by AdenaG** [comment]
@juanmriosv 
Alignment look better. Are you making the quickview under the other sections mentioned above look the same?

**Comment by juanmriosv** [comment]
@AdenaG Quick view has a different process and layout in the DOM. Not showing on mobile for example.

**Comment by c21hornak** [comment]
![screen shot 2017-01-04 at 3 12 38 pm](https://cloud.githubusercontent.com/assets/19403001/21657472/65412e08-d290-11e6-98f8-7625d2920cf9.png)

**Comment by c21hornak** [comment]
There seems to be an issue in quickview when the item is sold out.

**Comment by c21hornak** [comment]
Closing.
