### ISSUE TITLE
Tiered Pricing Changes on Master Product Pages - V2

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#43]
https://www.c21stores.com/products/legends-softside-upright-spinner?via=5851a63669702d432b00160c%2C5851b8a369702d2a5700539d

https://www.c21stores.com/products/amber-bath-collection?via=5851a63669702d432b00160c%2C5851b8a369702d2a5700539d

**Comment by juanmriosv** [comment]
All yours @AdenaG 
Done.

**Comment by AdenaG** [comment]
@juanmriosv

Savings look a little far to the left on master style parent and definitely too far away on the children tied to them on desktop.
On tablet & mobile, its even further, and alignment if off.

See screenshots
![master style desktop](https://cloud.githubusercontent.com/assets/20344050/21623982/f423fc36-d1d2-11e6-984a-13bc69313b59.png)
![master style tablet 4 33 09 pm](https://cloud.githubusercontent.com/assets/20344050/21623990/faecec26-d1d2-11e6-905c-619e01761d1a.png)
![master style mobile](https://cloud.githubusercontent.com/assets/20344050/21623995/fce80218-d1d2-11e6-9949-2d3422e7fd93.png)

**Comment by juanmriosv** [comment]
Thanks @AdenaG I forgot the child elements.
Let's talk about mobile tomorrow with Michael/

Best,

Juan

**Comment by juanmriosv** [comment]
All done @AdenaG,

I've tightened all up, the text aligment on mobile has to stay to the right.

**Comment by AdenaG** [comment]
@juanmriosv 
The children look good - mobile too. Suggestion - add just a tiny fraction of a space on the parent between percent off and the rest since on smaller devices, there is no space between the % and the $. 
![screen shot 2017-01-04 at 2 04 34 pm](https://cloud.githubusercontent.com/assets/20344050/21655141/bf8b29cc-d286-11e6-9c69-764f1d2a651e.png)

**Comment by c21hornak** [comment]
Approved to push to PROD @juanmriosv

**Comment by c21hornak** [comment]
@juanmriosv is there anything remaining to do for this, or can I close this?

**Comment by juanmriosv** [comment]
I believe this one is done as it.

**Comment by c21hornak** [comment]
Closing.
