### ISSUE TITLE
PDP Fixes for Safari

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/GLOBAL#45]
**Issue:** Customs scripts are not running on PDPs.
Examples of scripts not working:

- [x] Splited Global Header

- [x] Jewelry tech Video 

- [x] PDF knives

This happens ramdonly.

**Sample Links:**
https://www.c21stores.com/products/3pcslvrpntparing?via=56e9686969702d1229000125%2C56e968a969702d122900014f#1

**Screenshot:**
![screen shot 2017-01-04 at 11 21 11 am](https://cloud.githubusercontent.com/assets/16789090/21649654/73865dbe-d270-11e6-8415-c84c7611be95.png)

**Comment by juanmriosv** [comment]
@AdenaG 
This is done on and ready to QA on [JMPrototype.](https://www.c21stores.com/pages/jmprototype)

**Comment by AdenaG** [comment]
PASS in STAGING

**Comment by c21hornak** [comment]
Approved to push to PROD @juanmriosv

**Comment by c21hornak** [comment]
@juanmriosv does the "PUSH TO PRODUCTION" status mean it is pending a push to PROD? Or it has already been pushed to PROD?

**Comment by c21hornak** [comment]
Closing.
