### ISSUE TITLE
CLICKABLE IMAGES

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#5]

**Comment by AdenaG** [comment]
Question - do requirements for these clickable images also include the option to have the image linking to one place while the CTA links to another and/or image mapping on the assets? And do we want the copy above the CTA to be clickable?

**Comment by juanmriosv** [comment]
No, they image is a clone of the CTA. they both link to the same place. So far only images are clickable (and copy that is inside image)

**Comment by AdenaG** [comment]
k tnx. copy actually was clickable for me in all but IE v. 10.0.9200

**Comment by c21hornak** [comment]
Approved to push to PROD.

**Comment by c21hornak** [comment]
Juan pushed all to PROD on 7/26.
