### ISSUE TITLE
Top Banner Home Page (only) Message  During Physical Inventory

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#50]

**Comment by juanmriosv** [comment]
Ready for QA (staging)
# **DESKTOP**
![screen shot 2017-01-19 at 10 57 32 am](https://cloud.githubusercontent.com/assets/16789090/22114134/66104ccc-de36-11e6-90d3-c4dda1cb3d23.png)


# **MOBILE**
![screen shot 2017-01-19 at 11 02 22 am](https://cloud.githubusercontent.com/assets/16789090/22114263/d8251950-de36-11e6-81a3-edc3bae29e59.png)

**Comment by juanmriosv** [comment]
Pushed to production - Release 51F.

**Comment by AdenaG** [comment]
Pass in Prod

**Comment by c21hornak** [comment]
Closing.
