### ISSUE TITLE
Add a Confirmation Message on the Contact Us Page

### ISSUE THREAD

**Issue by c21hornak** [Century21Stores/GLOBAL#54]
https://www.c21stores.com/contact

Once a guest submits the form, they should receive some kind of confirmation that we received the message and will get back to them as soon as possible.

**Comment by c21hornak** [comment]
Used to be https://github.com/Century21Stores/LANDING-PAGES/issues/20

**Comment by juanmriosv** [comment]
@c21hornak 
I believe this is here:

https://github.com/Century21Stores/SPECIAL/issues/16

**Comment by c21hornak** [comment]
Wow I duplicated this twice..haha. Closing.
