### ISSUE TITLE
Bug: Spring Weekend Global Banner Displays on HP

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#74]
When I click to HP through email Responsys link, the global banner displays on the HP – desktop & mobile.

https://www.c21stores.com/?cm_ven=Responsys&cm_cat=Promotional&cm_pla=20170414-week11-FRI&cm_ite=GNU_Shop_Now_fri&utm_source=Responsys&utm_medium=email&utm_campaign=20170414-week11-FRI&utm_content=Promotional&utm_term=GNU_Shop_Now_fri&bcid=f15ca1dd48f571c64c65a9a85adbc3ef

![screen shot 2017-04-14 at 9 01 58 am](https://cloud.githubusercontent.com/assets/16789090/25043853/0eff7220-20f1-11e7-84ad-b22c0ce7d33d.png)

**Comment by juanmriosv** [comment]
Done

**Comment by c21hornak** [comment]
Closing.
