### ISSUE TITLE
Two-Column Hero/Half-Hero - Clickable Images

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#8]

**Comment by AdenaG** [comment]
Are these all in STAGING unless otherwise noted? And which category/page can I find it?

**Comment by juanmriosv** [comment]
I built all of them on the home page @AdenaG

**Comment by AdenaG** [comment]
Pass in STAGING

**Comment by c21hornak** [comment]
https://www.staging.c21.weblinc.com/pages/jmtwocolumn

**Comment by c21hornak** [comment]
Approved to push to PROD.

**Comment by c21hornak** [comment]
Juan pushed to PROD on 7/26.
